#!/usr/bin/env python
from __future__ import annotations


import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import argparse
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader

from aasunet.config import load_config
from aasunet.data.dataset import CTVolumeDataset, load_manifest
from aasunet.data.io import save_nifti
from aasunet.engine.inferer import sliding_window_inference
from aasunet.models.factory import build_model
from aasunet.utils.checkpoint import load_checkpoint
from aasunet.utils.visualization import save_slice_triplet


@torch.no_grad()
def predict_case(model, image, cfg, device):
    logits = sliding_window_inference(
        image.to(device),
        roi_size=cfg.data.patch_size,
        sw_batch_size=cfg.validation.sliding_window_batch,
        predictor=model,
        overlap=cfg.validation.overlap,
        use_gaussian=cfg.validation.use_gaussian,
    )
    return torch.argmax(logits, dim=1)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run inference with AAsU-Net.")
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--checkpoint", required=True, type=Path)
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--set", nargs="*", default=[])
    args = parser.parse_args()

    cfg = load_config(args.config, overrides=args.set)
    if args.manifest is None:
        raise ValueError("This inference script expects a manifest generated by prepare_kits.py or make_splits.py.")

    dataset = CTVolumeDataset(load_manifest(args.manifest), cfg, training=False)
    loader = DataLoader(dataset, batch_size=1, shuffle=False, num_workers=0)

    device = torch.device(cfg.runtime.device if torch.cuda.is_available() else "cpu")
    model = build_model(cfg).to(device)
    ckpt = load_checkpoint(args.checkpoint, map_location=device)
    model.load_state_dict(ckpt["model"], strict=True)
    model.eval()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    for batch in loader:
        meta = batch["meta"]
        case_id = meta["case_id"][0] if isinstance(meta["case_id"], list) else meta["case_id"]
        affine = meta["affine"][0].numpy() if isinstance(meta["affine"], torch.Tensor) else np.asarray(meta["affine"][0])
        prediction = predict_case(model, batch["image"], cfg, device).cpu().numpy()[0]
        save_nifti(prediction.astype(np.int16), affine, args.output_dir / f"{case_id}_pred.nii.gz")
        save_slice_triplet(batch["image"].numpy()[0], batch.get("label", None).numpy()[0] if "label" in batch else None, prediction, args.output_dir / f"{case_id}_preview.png")
        print(f"[OK] saved prediction for {case_id}")


if __name__ == "__main__":
    main()
